-- Generated by scripts/generate-seed-sql.js. Do not edit by hand.
-- Reset and repopulate example seed tables.

truncate table public.example_seed_tabs, public.example_seed_songs restart identity cascade;

insert into public.example_seed_songs (id, title, artist, key, tempo, structure, progression, lyrics, notes, sort_order)
values ('00000000-0000-0000-0000-000000000001', 'Careless Whisper', 'George Michael / Wham!', 'Dm', '76 BPM', 'Intro sax → Verse → Pre-chorus → Chorus → Verse → Pre-chorus → Chorus → Sax solo → Chorus → Outro', 'Dm  -  Bbmaj7  -  Gm7  -  A7', '', 'Saxo en Dm. Si lo tocás en guitarra, podés usar slide o bending para imitar el fraseo del sax.', 0);
insert into public.example_seed_tabs (song_id, title, content, position) values ('00000000-0000-0000-0000-000000000001', 'Sax riff principal (en guitarra, key Dm)', 'e|----------------------------------------|
B|----------------------------------------|
G|--10-7-5-3---5-3-2-0--------------------|
D|-----------5---------5-3-2-0------------|
A|----------------------------3-2-0-------|
E|----------------------------------------|', 0);

insert into public.example_seed_songs (id, title, artist, key, tempo, structure, progression, lyrics, notes, sort_order)
values ('00000000-0000-0000-0000-000000000002', 'Heart of Glass', 'Blondie', 'E', '116 BPM (4/4 disco)', 'Intro → Verse 1 → Chorus → Verse 2 → Chorus → Bridge instrumental → Verse → Chorus → Outro', 'E  -  A  -  B  (verse / chorus alternan con bridge en E - E7 - A - A#dim - B)', '', 'Feel disco/four-on-the-floor. Mantener constante el groove de hi-hat.', 1);
insert into public.example_seed_tabs (song_id, title, content, position) values ('00000000-0000-0000-0000-000000000002', 'Bajo / ostinato (figura disco)', 'G|--------------------|
D|--------------------|
A|--7--7-9-7--5-------|
E|--------------------|', 0);

insert into public.example_seed_songs (id, title, artist, key, tempo, structure, progression, lyrics, notes, sort_order)
values ('00000000-0000-0000-0000-000000000003', 'Hot Stuff', 'Donna Summer', 'Am', '120 BPM', 'Intro → Verse → Chorus → Verse → Chorus → Guitar solo → Chorus → Outro', 'Am  -  G  -  F  -  E7', '', 'Solo de guitarra es la parte icónica — vale la pena practicarlo bien.', 2);
insert into public.example_seed_tabs (song_id, title, content, position) values ('00000000-0000-0000-0000-000000000003', 'Riff principal de guitarra', 'e|----------------------------|
B|----------------------------|
G|--5-5-5-7-5-----------------|
D|------------7-5-7-5---------|
A|--------------------7-5-----|
E|----------------------------|', 0);

insert into public.example_seed_songs (id, title, artist, key, tempo, structure, progression, lyrics, notes, sort_order)
values ('00000000-0000-0000-0000-000000000004', 'Smalltown Boy', 'Bronski Beat', 'Cm', '138 BPM', 'Intro arpegio → Verse → Chorus → Verse → Chorus → Break → Chorus → Outro', 'Cm  -  Ab  -  Eb  -  Bb', '', 'El groove está en el arpegio constante. Usar delay si tienen.', 3);
insert into public.example_seed_tabs (song_id, title, content, position) values ('00000000-0000-0000-0000-000000000004', 'Arpegio sintetizador principal (adaptado guitarra)', 'e|--3-6-8-6-3---3-6-8-6-3---|
B|--------------------------|
G|--------------------------|
D|--------------------------|
A|--------------------------|
E|--------------------------|', 0);

insert into public.example_seed_songs (id, title, artist, key, tempo, structure, progression, lyrics, notes, sort_order)
values ('00000000-0000-0000-0000-000000000005', 'Georgy Porgy', 'Toto', 'F#m7', '104 BPM (smooth funk)', 'Intro → Verse → Pre → Chorus → Verse → Pre → Chorus → Solo → Chorus → Outro', 'F#m7  -  B7  -  E maj7  -  A maj7  (típica progresión II-V smooth)', '', 'Acordes con extensiones (maj7, 9). No tocar power chords — perdería el carácter.', 4);
insert into public.example_seed_tabs (song_id, title, content, position) values ('00000000-0000-0000-0000-000000000005', 'Riff intro (estilo Lukather)', 'e|--------------------------------|
B|--7-9--7--5-7-5-----------------|
G|----------------6-4-6-----------|
D|----------------------7---------|
A|--------------------------------|
E|--------------------------------|', 0);

insert into public.example_seed_songs (id, title, artist, key, tempo, structure, progression, lyrics, notes, sort_order)
values ('00000000-0000-0000-0000-000000000006', 'Love Her Madly', 'The Doors', 'Am', '112 BPM', 'Intro → Verse → Chorus → Verse → Chorus → Organ solo → Verse → Chorus → Outro', 'Verse: Am  -  G  -  F  -  E7   |   Chorus: Dm  -  Am  -  E7  -  Am', '', 'El órgano lleva el peso melódico. La guitarra puede hacer rítmica simple.', 5);
insert into public.example_seed_tabs (song_id, title, content, position) values ('00000000-0000-0000-0000-000000000006', 'Riff intro de guitarra', 'e|--0---0---0---0---|
B|--1---1---1---1---|
G|--2---0---2---2---|
D|--2---2---2---0---|
A|--0---3---0-------|
E|--------------0---|', 0);

insert into public.example_seed_songs (id, title, artist, key, tempo, structure, progression, lyrics, notes, sort_order)
values ('00000000-0000-0000-0000-000000000007', 'Call Mr. Lee', 'Television', 'G', '120 BPM', 'Intro riff → Verse → Chorus → Verse → Chorus → Guitar solo → Verse → Outro', 'G  -  D  -  C  -  G', '', 'Dos guitarras entrelazadas — característica de Television. Tono limpio con leve chorus.', 6);
insert into public.example_seed_tabs (song_id, title, content, position) values ('00000000-0000-0000-0000-000000000007', 'Riff principal (estilo Verlaine)', 'e|-------------------------|
B|--3-3-3-3----------------|
G|--4-4-4-4---0-2-0--------|
D|--5-5-5-5---2-3-2--------|
A|-------------------------|
E|-------------------------|', 0);

insert into public.example_seed_songs (id, title, artist, key, tempo, structure, progression, lyrics, notes, sort_order)
values ('00000000-0000-0000-0000-000000000008', 'My Favourite Game', 'The Cardigans', 'F#m', '118 BPM', 'Intro → Verse → Pre → Chorus → Verse → Pre → Chorus → Bridge → Chorus → Outro', 'F#m  -  D  -  A  -  E', '', 'Distorsión potente en el riff, pero la voz canta sobre acordes limpios alternativamente.', 7);
insert into public.example_seed_tabs (song_id, title, content, position) values ('00000000-0000-0000-0000-000000000008', 'Riff principal distorsionado', 'e|--2-2-2-2-2-2-2-2-|
B|--2-2-2-2-2-2-2-2-|
G|--2-2-2-2-2-2-2-2-|
D|--4-4-4-4-4-4-4-4-|
A|--4-4-4-4-4-4-4-4-|
E|--2-2-2-2-2-2-2-2-|', 0);

insert into public.example_seed_songs (id, title, artist, key, tempo, structure, progression, lyrics, notes, sort_order)
values ('00000000-0000-0000-0000-000000000009', 'In Bloom', 'Nirvana', 'Bb', '78 BPM (half-time feel)', 'Intro → Verse → Pre → Chorus → Verse → Pre → Chorus → Solo → Verse → Chorus → Outro', 'Verse: Bb  -  Ab  -  Db  -  Gb   |   Chorus: Eb  -  Ab  -  Db  -  Bb', '', 'Bajar medio tono (Eb tuning) si querés tono original. Si no, en standard suena igual de bien.', 8);
insert into public.example_seed_tabs (song_id, title, content, position) values ('00000000-0000-0000-0000-000000000009', 'Riff intro principal', 'e|-------------------------------|
B|-------------------------------|
G|-------------------------------|
D|--8-8-8-8-6-6-4-4--------------|
A|--8-8-8-8-6-6-4-4--------------|
E|--6-6-6-6-4-4-2-2--------------|', 0);

insert into public.example_seed_songs (id, title, artist, key, tempo, structure, progression, lyrics, notes, sort_order)
values ('00000000-0000-0000-0000-000000000010', 'Lithium', 'Nirvana', 'D', '60 BPM', 'Intro/Verse → Chorus → Verse → Chorus → Verse → Chorus → Outro', 'D  -  F#  -  B  -  G  -  Bb  -  C  -  A', '', 'Dinámica suave/fuerte clásica de Nirvana. Verse limpio, chorus distorsionado.', 9);
insert into public.example_seed_tabs (song_id, title, content, position) values ('00000000-0000-0000-0000-000000000010', 'Progresión principal (power chords)', 'e|-----------------------------|
B|-----------------------------|
G|-----------------------------|
D|--7-11-9-5-8-10-7------------|
A|--5--9-7-3-6--8-5------------|
E|-----------------------------|', 0);

insert into public.example_seed_songs (id, title, artist, key, tempo, structure, progression, lyrics, notes, sort_order)
values ('00000000-0000-0000-0000-000000000011', 'Vicar in a Tutu', 'The Smiths', 'G', '150 BPM (rockabilly feel)', 'Intro → Verse → Chorus → Verse → Chorus → Solo → Verse → Chorus → Outro', 'G  -  C  -  D  -  G', '', 'Estilo arpegiado característico de Johnny Marr. Capo en 2 si querés el tono original (sube a A).', 10);
insert into public.example_seed_tabs (song_id, title, content, position) values ('00000000-0000-0000-0000-000000000011', 'Riff Marr — rockabilly arpegiado', 'e|--3-----3-----3-----3-----|
B|----3-----3-----3-----3---|
G|------0-----0-----0-----0-|
D|--------------------------|
A|--------------------------|
E|--3-----3-----3-----3-----|', 0);

insert into public.example_seed_songs (id, title, artist, key, tempo, structure, progression, lyrics, notes, sort_order)
values ('00000000-0000-0000-0000-000000000012', 'Fell in Love with a Girl', 'The White Stripes', 'E', '153 BPM', 'Intro → Verse → Chorus → Verse → Chorus → Bridge → Chorus → Outro', 'E  -  G  -  A  -  C', '', 'Power chords agresivos, sin pausas. Distorsión bien sucia.', 11);
insert into public.example_seed_tabs (song_id, title, content, position) values ('00000000-0000-0000-0000-000000000012', 'Riff principal', 'e|---------------------|
B|---------------------|
G|---------------------|
D|--2-2-5-5-7-7-10-10--|
A|--2-2-5-5-7-7-10-10--|
E|--0-0-3-3-5-5--8--8--|', 0);

insert into public.example_seed_songs (id, title, artist, key, tempo, structure, progression, lyrics, notes, sort_order)
values ('00000000-0000-0000-0000-000000000013', 'White Wedding', 'Billy Idol', 'Am', '138 BPM', 'Intro riff → Verse → Pre → Chorus → Verse → Pre → Chorus → Solo → Chorus → Outro', 'Am  -  F  -  G  -  E', '', 'Tempo marcado, feel oscuro. La intro es ICÓNICA — ensayarla bien.', 12);
insert into public.example_seed_tabs (song_id, title, content, position) values ('00000000-0000-0000-0000-000000000013', 'Riff intro principal', 'e|-----------------------|
B|-----------------------|
G|-----------------------|
D|--7-7-5-7-5-7--5-------|
A|--7-7-5-7-5-7--5-------|
E|--5-5-3-5-3-5--3-------|', 0);

insert into public.example_seed_songs (id, title, artist, key, tempo, structure, progression, lyrics, notes, sort_order)
values ('00000000-0000-0000-0000-000000000014', 'Breed', 'Nirvana', 'B', '159 BPM', 'Intro → Verse → Chorus → Verse → Chorus → Solo → Chorus → Outro', 'B  -  A  -  E   (basado en pedal de B)', '', 'Velocidad y energía. Palm muting en las partes bajas, todo abierto en chorus.', 13);
insert into public.example_seed_tabs (song_id, title, content, position) values ('00000000-0000-0000-0000-000000000014', 'Riff principal', 'e|--------------------------|
B|--------------------------|
G|--------------------------|
D|--9-9-9-9-7-7-7-7-2-2-----|
A|--9-9-9-9-7-7-7-7-2-2-----|
E|--7-7-7-7-5-5-5-5-0-0-----|', 0);

insert into public.example_seed_songs (id, title, artist, key, tempo, structure, progression, lyrics, notes, sort_order)
values ('00000000-0000-0000-0000-000000000015', 'Rebel Yell', 'Billy Idol', 'F#m', '126 BPM', 'Intro → Verse → Pre → Chorus → Verse → Pre → Chorus → Solo → Chorus → Outro', 'F#m  -  E  -  D  -  A', '', 'El solo de Steve Stevens es muy técnico — si no llegan, pueden hacer una versión simplificada.', 14);
insert into public.example_seed_tabs (song_id, title, content, position) values ('00000000-0000-0000-0000-000000000015', 'Riff intro (Steve Stevens)', 'e|-----------------------------|
B|-----------------------------|
G|--11-11-9-11-9-7-------------|
D|--11-11-9-11-9-7-------------|
A|--9--9--7-9--7-5-------------|
E|-----------------------------|', 0);

insert into public.example_seed_songs (id, title, artist, key, tempo, structure, progression, lyrics, notes, sort_order)
values ('00000000-0000-0000-0000-000000000016', 'Muskrat Love', 'America', 'G', '104 BPM', 'Intro → Verse → Chorus → Verse → Chorus → Bridge → Verse → Chorus → Outro', 'G  -  Em  -  C  -  D', '', 'Folk suave. Fingerpicking si pueden, sino strumming gentil.', 15);
insert into public.example_seed_tabs (song_id, title, content, position) values ('00000000-0000-0000-0000-000000000016', 'Patrón arpegiado intro', 'e|--3-----0-----0-----2---|
B|----0-----0-----1-----3-|
G|------0-----0-----0-----|
D|--------2-----2-----0---|
A|--2---------3-----------|
E|--------------------3---|', 0);

insert into public.example_seed_songs (id, title, artist, key, tempo, structure, progression, lyrics, notes, sort_order)
values ('00000000-0000-0000-0000-000000000017', 'Tin Man', 'America', 'G', '108 BPM', 'Intro → Verse → Chorus → Verse → Chorus → Bridge → Chorus → Outro', 'G  -  Bm  -  Am  -  D  -  Em  -  C', '', 'Capo en traste 2 para tonalidad original. Doce cuerdas si tienen — agrega magia.', 16);
insert into public.example_seed_tabs (song_id, title, content, position) values ('00000000-0000-0000-0000-000000000017', 'Intro acústica (capo 2 → suena en A)', 'e|--3---2---0---2--|
B|--3---3---1---3--|
G|--0---4---0---2--|
D|--0---4---2---0--|
A|--2---2---3------|
E|--3-----------2--|', 0);

insert into public.example_seed_songs (id, title, artist, key, tempo, structure, progression, lyrics, notes, sort_order)
values ('00000000-0000-0000-0000-000000000018', 'You Can Do Magic', 'America', 'D', '112 BPM', 'Intro → Verse → Pre → Chorus → Verse → Pre → Chorus → Bridge → Chorus → Outro', 'D  -  A  -  Bm  -  G', '', 'Pop suave de los 80s. Mantener el groove constante.', 17);
insert into public.example_seed_tabs (song_id, title, content, position) values ('00000000-0000-0000-0000-000000000018', 'Strumming pattern', 'e|--2---0---2---3-----|
B|--3---2---3---3-----|
G|--2---2---4---0-----|
D|--0---2---4---0-----|
A|------0---2---2-----|
E|--------------3-----|', 0);

insert into public.example_seed_songs (id, title, artist, key, tempo, structure, progression, lyrics, notes, sort_order)
values ('00000000-0000-0000-0000-000000000019', 'Ventura Highway', 'America', 'B', '92 BPM', 'Intro → Verse → Chorus → Verse → Chorus → Solo → Chorus → Outro', 'B  -  Bsus4  (intro)  →  F#m  -  Em', '', 'El riff intro hay que loopearlo durante todo el verso. Suena espacioso.', 18);
insert into public.example_seed_tabs (song_id, title, content, position) values ('00000000-0000-0000-0000-000000000019', 'Intro riff icónica (capo opcional traste 2)', 'e|--2-2-2-2-2-2-2-2-|
B|--4-5-4-2-4-5-4-2-|
G|--4-4-4-4-4-4-4-4-|
D|--4-4-4-4-4-4-4-4-|
A|------------------|
E|------------------|', 0);

insert into public.example_seed_songs (id, title, artist, key, tempo, structure, progression, lyrics, notes, sort_order)
values ('00000000-0000-0000-0000-000000000020', 'No Podrás', 'Cristian Castro', 'G', '120 BPM (balada pop)', 'Intro → Verse → Pre → Chorus → Verse → Pre → Chorus → Puente → Chorus → Outro', 'G  -  D/F#  -  Em  -  C  -  G  -  D  -  C  -  D', '', 'Balada pop latino. Teclado suele llevar el arpegio. Voz muy expuesta — atención al volumen.', 19);
insert into public.example_seed_tabs (song_id, title, content, position) values ('00000000-0000-0000-0000-000000000020', 'Sugerencia: arpegio teclado / guitarra limpia', 'e|--3---2---0---0---|
B|--3---3---0---1---|
G|--0---2---0---0---|
D|--0---0---2---2---|
A|--2-------2---3---|
E|--3---------------|', 0);

insert into public.example_seed_songs (id, title, artist, key, tempo, structure, progression, lyrics, notes, sort_order)
values ('00000000-0000-0000-0000-000000000021', 'Young Turks', 'Rod Stewart', 'A', '120 BPM', 'Intro sintetizador → Verse → Chorus → Verse → Chorus → Bridge → Chorus → Outro', 'A  -  E  -  F#m  -  D', '', 'Sintetizador 80s muy característico. Si no hay teclado, guitarra con delay funciona bien.', 20);
insert into public.example_seed_tabs (song_id, title, content, position) values ('00000000-0000-0000-0000-000000000021', 'Riff sintetizador adaptado a guitarra', 'e|--5-----5-----5-----5-----|
B|----5-----5-----5-----5---|
G|------6-----6-----6-----6-|
D|--------------------------|
A|--------------------------|
E|--------------------------|', 0);

insert into public.example_seed_songs (id, title, artist, key, tempo, structure, progression, lyrics, notes, sort_order)
values ('00000000-0000-0000-0000-000000000022', 'It Could Happen to You', 'Chet Baker (jazz standard)', 'Eb (vocal) / varias', 'Medium swing ~140 BPM', 'Head → Solos (chord changes) → Head out', 'Eb maj7  -  E dim7  -  Fm7  -  Bb7  -  Gm7  -  Cm7  -  Fm7  -  Bb7', '', 'Standard de jazz. Ensayar cambios. Voicings con extensiones (7, 9, 13). Comping suave.', 21);
insert into public.example_seed_tabs (song_id, title, content, position) values ('00000000-0000-0000-0000-000000000022', 'Comping suggestion (shells)', 'Ebmaj7      Edim7       Fm7         Bb7
e|--7--      e|--8--      e|--8--      e|--6--
B|--8--      B|--7--      B|--6--      B|--6--
G|--7--      G|--8--      G|--8--      G|--7--
D|--8--      D|--7--      D|--6--      D|--5--', 0);

insert into public.example_seed_songs (id, title, artist, key, tempo, structure, progression, lyrics, notes, sort_order)
values ('00000000-0000-0000-0000-000000000023', 'Something', 'The Beatles (George Harrison)', 'C', '66 BPM', 'Intro → Verse → Bridge → Verse → Solo → Bridge → Verse → Outro', 'C  -  Cmaj7  -  C7  -  F  -  D7  -  G', '', 'Riff intro tan icónico como la canción. Limpio, con leve reverb.', 22);
insert into public.example_seed_tabs (song_id, title, content, position) values ('00000000-0000-0000-0000-000000000023', 'Intro riff (Harrison)', 'e|--0---------0------|
B|--1-1-3-1---1-1-3--|
G|--0---0-0---0---0--|
D|--2---2-2---2---2--|
A|--3---------3------|
E|-------------------|', 0);

insert into public.example_seed_songs (id, title, artist, key, tempo, structure, progression, lyrics, notes, sort_order)
values ('00000000-0000-0000-0000-000000000024', 'While My Guitar Gently Weeps', 'The Beatles', 'Am', '115 BPM', 'Intro → Verse → Chorus → Verse → Chorus → Solo (Clapton) → Verse → Outro extendido', 'Verse: Am  -  Am/G  -  D9/F#  -  F   |   Chorus: A  -  C#m  -  F#m  -  C#m  -  Bm  -  E', '', 'Si va el solo de Clapton, prepararlo aparte. Hay versión simple y versión con solo épico.', 23);
insert into public.example_seed_tabs (song_id, title, content, position) values ('00000000-0000-0000-0000-000000000024', 'Intro (Beatles - acústica fingerpicked)', 'e|--0-----0-----2-----1-----|
B|--1-----1-----3-----1-----|
G|--2-----0-----2-----2-----|
D|--2-----2-----0-----3-----|
A|--0-----2-----------------|
E|--------3-----------------|', 0);

insert into public.example_seed_songs (id, title, artist, key, tempo, structure, progression, lyrics, notes, sort_order)
values ('00000000-0000-0000-0000-000000000025', 'Golden Slumbers', 'The Beatles', 'A minor / C major', '78 BPM', 'Verse → Chorus → Verse → Chorus → (segue a Carry That Weight)', 'Am7  -  Dm7  -  G7  -  C  -  F  -  Em  -  Am  -  Dm7  -  G7  -  C', '', 'Tema corto pero muy emotivo. Suele ir antes de ''Carry That Weight''. Si lo hacen como medley, prepararlo.', 24);
insert into public.example_seed_tabs (song_id, title, content, position) values ('00000000-0000-0000-0000-000000000025', 'Piano voicings adaptados (acordes con tensión)', 'Am7    Dm7    G7     C
e|--0    e|--1    e|--1    e|--0
B|--1    B|--1    B|--0    B|--1
G|--0    G|--2    G|--0    G|--0
D|--2    D|--0    D|--0    D|--2
A|--0          A|--3
E|', 0);

insert into public.example_seed_songs (id, title, artist, key, tempo, structure, progression, lyrics, notes, sort_order)
values ('00000000-0000-0000-0000-000000000026', 'L.A. Woman', 'The Doors', 'A', '118 BPM', 'Intro → Verse → Chorus → Verse → Chorus → Bridge (Mr. Mojo Risin'') → Chorus → Outro', 'A  -  D  -  E  (12-bar blues based con variaciones)', '', 'Tema largo (7+ min). Tiene sección ''Mr. Mojo Risin'' que sube tempo gradualmente. Prepararlo.', 25);
insert into public.example_seed_tabs (song_id, title, content, position) values ('00000000-0000-0000-0000-000000000026', 'Riff principal', 'e|-----------------|
B|-----------------|
G|--2--------------|
D|--2-0-2-0-2------|
A|--0--------------|
E|-----------------|', 0);

insert into public.example_seed_songs (id, title, artist, key, tempo, structure, progression, lyrics, notes, sort_order)
values ('00000000-0000-0000-0000-000000000027', 'Self Control', 'Laura Branigan', 'Am', '120 BPM', 'Intro → Verse → Pre → Chorus → Verse → Pre → Chorus → Bridge → Chorus → Outro', 'Am  -  G  -  F  -  E7', '', '80s synth-pop dramático. Voz con mucho protagonismo. Reverb en todo.', 26);
insert into public.example_seed_tabs (song_id, title, content, position) values ('00000000-0000-0000-0000-000000000027', 'Riff sintetizador adaptado', 'e|--5-5-5-5-5-5-5-5-|
B|--5-5-5-5-5-5-5-5-|
G|--5-5-5-5-5-5-5-5-|
D|--7-7-5-5-3-3-2-2-|
A|------------------|
E|------------------|', 0);

insert into public.example_seed_songs (id, title, artist, key, tempo, structure, progression, lyrics, notes, sort_order)
values ('00000000-0000-0000-0000-000000000028', 'Toxic Girl', 'Kings of Convenience', 'G', '120 BPM', 'Intro → Verse → Chorus → Verse → Chorus → Bridge → Chorus → Outro', 'G  -  D  -  Em  -  C', '', 'Estilo Simon & Garfunkel. Dos guitarras acústicas entrelazadas, voces en armonía.', 27);
insert into public.example_seed_tabs (song_id, title, content, position) values ('00000000-0000-0000-0000-000000000028', 'Fingerpicking acústico', 'e|--3-----2-----0-----0---|
B|----0-----3-----0-----1-|
G|------0-----2-----0---0-|
D|--0-----0-----2-----2---|
A|--2---------2-----3-----|
E|--3---------------------|', 0);

insert into public.example_seed_songs (id, title, artist, key, tempo, structure, progression, lyrics, notes, sort_order)
values ('00000000-0000-0000-0000-000000000029', 'Aún Estás en Mis Sueños', 'Rata Blanca', 'Em', '75 BPM (balada rock)', 'Intro → Verse → Chorus → Verse → Chorus → Solo → Chorus → Outro', 'Em  -  C  -  G  -  D  -  Am  -  B7', '', 'Solo de Giardino es el alma del tema. Prepararlo bien o hacer versión simplificada.', 28);
insert into public.example_seed_tabs (song_id, title, content, position) values ('00000000-0000-0000-0000-000000000029', 'Arpegio intro (estilo Walter Giardino)', 'e|--0-3-0-----0-1-0-----|
B|------3-0-------1-0---|
G|------0-----------0---|
D|--2-----------2-------|
A|--2-----------3-------|
E|--0-------------------|', 0);

insert into public.example_seed_songs (id, title, artist, key, tempo, structure, progression, lyrics, notes, sort_order)
values ('00000000-0000-0000-0000-000000000030', 'Eyes Without a Face', 'Billy Idol', 'C#m', '92 BPM', 'Intro → Verse → Chorus → Verse → Chorus → Bridge (cambio de feel rock) → Chorus → Outro', 'C#m  -  A  -  E  -  B', '', 'Tema con dos secciones muy distintas: la suave con coros ''les yeux sans visage'' y la sección rock del medio.', 29);
insert into public.example_seed_tabs (song_id, title, content, position) values ('00000000-0000-0000-0000-000000000030', 'Arpegio limpio intro', 'e|--4-----0-----0-----2-----|
B|----5-----2-----0-----4---|
G|--6-----1-----1-----4-----|
D|--6-----2-----2-----4-----|
A|--4-----0-----------2-----|
E|--------------0-----------|', 0);

insert into public.example_seed_songs (id, title, artist, key, tempo, structure, progression, lyrics, notes, sort_order)
values ('00000000-0000-0000-0000-000000000031', 'That Girl', 'Stevie Wonder', 'Bbm', '90 BPM', 'Intro → Verse → Chorus → Verse → Chorus → Bridge → Chorus → Outro', 'Bbm9  -  Eb9  -  Abmaj7  -  Dbmaj7', '', 'R&B sofisticado. Acordes con muchas extensiones. Groove fundamental — batería con feel suave.', 30);
insert into public.example_seed_tabs (song_id, title, content, position) values ('00000000-0000-0000-0000-000000000031', 'Voicings de guitarra con extensiones', 'Bbm9    Eb9     Abmaj7   Dbmaj7
e|--6    e|--6    e|--4     e|--4
B|--6    B|--6    B|--4     B|--6
G|--6    G|--5    G|--5     G|--5
D|--8    D|--6    D|--5     D|--6
A|--8    A|--6
E|', 0);

insert into public.example_seed_songs (id, title, artist, key, tempo, structure, progression, lyrics, notes, sort_order)
values ('00000000-0000-0000-0000-000000000032', 'Honesty', 'Billy Joel', 'Bb', '76 BPM', 'Intro piano → Verse → Chorus → Verse → Chorus → Bridge → Chorus → Outro', 'Bb  -  F/A  -  Gm  -  Eb  -  Bb/D  -  Cm  -  F', '', 'Tema muy pianístico. La guitarra debe acompañar suave. Voz expuesta — ensayar dinámica.', 31);
insert into public.example_seed_tabs (song_id, title, content, position) values ('00000000-0000-0000-0000-000000000032', 'Acordes principales (guitarra acompañamiento)', 'Bb       F/A      Gm       Eb
e|--1     e|--1     e|--3     e|--6
B|--3     B|--1     B|--3     B|--8
G|--3     G|--2     G|--3     G|--8
D|--3     D|--3     D|--5     D|--8
A|--1     A|--0
E|', 0);

insert into public.example_seed_songs (id, title, artist, key, tempo, structure, progression, lyrics, notes, sort_order)
values ('00000000-0000-0000-0000-000000000033', 'Just the Way You Are', 'Billy Joel', 'D', '120 BPM', 'Intro → Verse → Chorus → Verse → Chorus → Sax solo → Bridge → Chorus → Outro', 'Dmaj7  -  Bm7  -  Em7  -  A7', '', 'Solo de sax legendario. Si no tienen sax, hacerlo con guitarra limpia o teclado.', 32);
insert into public.example_seed_tabs (song_id, title, content, position) values ('00000000-0000-0000-0000-000000000033', 'Comping con séptimas', 'Dmaj7   Bm7     Em7     A7
e|--2    e|--2    e|--3    e|--5
B|--2    B|--3    B|--3    B|--5
G|--2    G|--2    G|--4    G|--6
D|--4    D|--4    D|--5    D|--5
A|       A|--2    A|       A|
E|', 0);

insert into public.example_seed_songs (id, title, artist, key, tempo, structure, progression, lyrics, notes, sort_order)
values ('00000000-0000-0000-0000-000000000034', 'What You Won''t Do for Love', 'Bobby Caldwell', 'F#m', '108 BPM (smooth soul)', 'Intro → Verse → Pre → Chorus → Verse → Pre → Chorus → Solo → Chorus → Outro', 'F#m7  -  B7  -  Emaj7  -  C#m7', '', 'Soul/jazz sofisticado. Rhodes piano clásico. Voz muy importante — feel relajado.', 33);
insert into public.example_seed_tabs (song_id, title, content, position) values ('00000000-0000-0000-0000-000000000034', 'Comping smooth (voicings de 7ma)', 'F#m7    B7      Emaj7   C#m7
e|--2    e|--2    e|--7    e|--4
B|--2    B|--4    B|--9    B|--5
G|--2    G|--2    G|--8    G|--4
D|--4    D|--4    D|--9    D|--6
A|--4    A|--2
E|--2    E|', 0);

insert into public.example_seed_songs (id, title, artist, key, tempo, structure, progression, lyrics, notes, sort_order)
values ('00000000-0000-0000-0000-000000000035', 'Bad Girls', 'Donna Summer', 'G', '131 BPM (disco)', 'Intro → Verse → Pre → Chorus → Verse → Pre → Chorus → Break → Chorus → Outro', 'G  -  C  -  D  -  G   (con riff de bajo característico)', '', 'Disco clásico. El bajo es protagónico. ''Toot toot, beep beep'' es el hook icónico.', 34);
insert into public.example_seed_tabs (song_id, title, content, position) values ('00000000-0000-0000-0000-000000000035', 'Riff de bajo principal', 'G|------------------|
D|------------------|
A|--5-5---5---5-3-5-|
E|------3-----------|', 0);

insert into public.example_seed_songs (id, title, artist, key, tempo, structure, progression, lyrics, notes, sort_order)
values ('00000000-0000-0000-0000-000000000036', 'Chega de Saudade', 'Antônio Carlos Jobim', 'Dm / D (modulación bossa)', 'Bossa nova ~140 BPM', 'Sección A (menor) → Sección B (mayor) → A → B → Outro', 'A: Dm  -  A7  -  Dm  -  Gm  -  A7  -  Dm   |   B: D  -  A7  -  D  -  G  -  A7  -  D', '', 'Bossa fundacional. Patrón rítmico de Gilberto: pulgar marca el bajo, dedos los acordes en contratiempo.', 35);
insert into public.example_seed_tabs (song_id, title, content, position) values ('00000000-0000-0000-0000-000000000036', 'Comping bossa nova (estilo João Gilberto)', 'Dm      A7      Gm      D
e|--1    e|--0    e|--3    e|--2
B|--3    B|--2    B|--3    B|--3
G|--2    G|--0    G|--3    G|--2
D|--0    D|--2    D|--5    D|--0
A|       A|--0    A|--5
E|       E|       E|--3', 0);

insert into public.example_seed_songs (id, title, artist, key, tempo, structure, progression, lyrics, notes, sort_order)
values ('00000000-0000-0000-0000-000000000037', 'Bigmouth Strikes Again', 'The Smiths', 'D', '166 BPM', 'Intro → Verse → Chorus → Verse → Chorus → Solo → Chorus → Outro', 'D  -  A  -  G  -  D', '', 'Capo en traste 2 para tono original. Estilo Marr: guitarras entrelazadas, mucho jangle.', 36);
insert into public.example_seed_tabs (song_id, title, content, position) values ('00000000-0000-0000-0000-000000000037', 'Riff Marr (intro con doble cuerda)', 'e|--2-2-2-2-5-5-5-5-3-3-3-3-2-2-2-2-|
B|--3-3-3-3-7-7-7-7-3-3-3-3-3-3-3-3-|
G|----------------------------------|
D|----------------------------------|
A|----------------------------------|
E|----------------------------------|', 0);
